### PR TITLE
Fix MiniMessage API Inserting code example

### PR DESCRIPTION
**Pull request by Dominilk01**

### CODE REVIEW

**Comment by zml2008** [comment]
this is incorrect

**Comment by Dominilk01** [comment]
image

**Comment by zml2008** [comment]
Did you test any of this? Are you able to communicate in full sentences? Is there any justification for this beyond "red line go away"?

**Comment by Dominilk01** [comment]
i mean i tested and it work

**Comment by zml2008** [comment]
correct fix here https://github.com/KyoriPowered/adventure-docs/commit/5a5fe4781b4645496db861769c8029515137e160

**Comment by Dominilk01** [comment]
Ok so i understand what i did wrong
I waned to create a builder that can only parse my tag. So yea its not realy inserting that i needed to do.

**Pull request closed without merging**
