### PR TITLE
feat(code-block): add copy to clipboard button

### PR DESCRIPTION
**Pull request by RohanGoyalDev**

### CODE REVIEW

**Comment by RohanGoyalDev** [comment]
image
The extension currently does not allow for this check SVG to be changed. If anyone can figure out a way to make that possible or add that feature to the [copy-button](https://github.com/executablebooks/sphinx-copybutton) extension use [this](https://icons.getbootstrap.com/icons/clipboard2-check/) SVG for adventure-docs

**Comment by MiniDigger** [comment]
I don't think that is a big problem tbh, looks good enough. 
to my eyes the copy button stroke looks a bit to wide, but that might be just me.

**Comment by kezz** [comment]
Can we just use the standard copy button that the extension uses? Do we have to provide our own?

**Comment by RohanGoyalDev** [comment]
changed to standard button

**Review by kezz — APPROVED** [review]
Awesome, I think the default one looks a lot cleaner tbh! Thanks for the PR!

**Review by zml2008 — APPROVED** [review]

**Pull request merged**
