### PR TITLE
add Core to Community Libraries

### PR DESCRIPTION
**Pull request by TureBentzin**
Addition of my Core to the list of Community Libraries.

I don't know if it is allowed to provide a GitHub and a Download link. If only one link is allowed I will remove the second one!

### CODE REVIEW

**Comment by zml2008** [comment]
As this documentation is mostly developer focused, I think it's best to just put in a GitHub link - that's consistent with the other projects here too.

**Comment by TureBentzin** [comment]
i will remove the Hangar link then

**Comment by kezz** [comment]
I'd prefer to keep the descriptions plain and feature-based - it should be easy to see exactly what using this library would provide a developer, particularly in the context of adventure

**Comment by TureBentzin** [comment]
I tried finding a small description that sums up the adventure part here

**Review by zml2008 — APPROVED** [review]

**Pull request merged**
