### PR TITLE
Stub out new community libraries page

### PR DESCRIPTION
**Pull request by zml2008**
This provides a convenient location to link to community-provided libraries

### CODE REVIEW

**Comment by Vankka** [comment]
[MCDiscordReserializer](https://github.com/Vankka/MCDiscordReserializer) Serializers for going between Minecraft & Discord

[EnhancedLegacyText](https://github.com/Vankka/EnhancedLegacyText) Alternative input format that is legacy compatible with new features

**Comment by NoahvdAa** [comment]
@stefvanschie's amazing [Inventory Framework](https://github.com/stefvanschie/IF) also has adventure support :)

**Comment by Majekdor** [comment]
[HexNicks](https://github.com/MajekDev/HexNicks) is a nicknaming plugin that uses adventure components and has full support for using MiniMessage tags in nicknames.

**Comment by broccolai** [comment]
> [HexNicks](https://github.com/MajekDev/HexNicks) is a nicknaming plugin that uses adventure components and has full support for using MiniMessage tags in nicknames.

We're looking for libraries, not plugins. Thank you though.

**Comment by ryantheleach** [comment]
I don't know one. 
But I'd love to see an opinionated I18N library that can handle any of the following:

minimessage template deserialization, using (yaml?) Resource bundles, default locale, migrating version changes, with support for user-customization.

**Comment by VytskaLT** [comment]
https://github.com/MegavexNetwork/scoreboard-library
Sidebar and Teams API

**Comment by ryantheleach** [comment]
Moonshine (or an opinionated, documented, library using it) Could be a good shout.

**Comment by zml2008** [comment]
Thanks to those who have suggested libraries so far! As we are now merging this PR, any further requests should be made as their own PRs.

**Pull request merged**
